package com.ledgora.common.enums;

public enum RoleName {
    ROLE_ADMIN, ROLE_MANAGER, ROLE_TELLER, ROLE_CUSTOMER,
    ROLE_MAKER, ROLE_CHECKER, ROLE_BRANCH_MANAGER, ROLE_TENANT_ADMIN, ROLE_SUPER_ADMIN
}
