<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ include file="../layout/header.jsp" %>
<link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/regulatory.css"/>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h3><i class="bi bi-clipboard2-data"></i> Balance Sheet — RBI Schedule 5</h3>
    <div>
        <span class="badge bg-dark me-2"><i class="bi bi-calendar3"></i> <c:out value="${businessDate}"/></span>
        <span class="eod-verified"><i class="bi bi-check-circle-fill"></i> EOD Verified</span>
    </div>
</div>
<%@ include file="../layout/status-banner.jsp" %>

<c:choose>
    <c:when test="${bsAvailable}">
        <%-- Equation Validation --%>
        <div class="alert ${bsData.balanceCheck ? 'alert-success' : 'alert-danger'} mb-4">
            <i class="bi ${bsData.balanceCheck ? 'bi-check-circle-fill' : 'bi-x-circle-fill'}"></i>
            <strong>Accounting Equation:</strong>
            Assets (<fmt:formatNumber value="${bsData.totalAssets}" maxFractionDigits="0"/>)
            = Liabilities (<fmt:formatNumber value="${bsData.totalLiabilities}" maxFractionDigits="0"/>)
            + Equity (<fmt:formatNumber value="${bsData.totalEquity}" maxFractionDigits="0"/>)
            — <c:choose><c:when test="${bsData.balanceCheck}">BALANCED</c:when><c:otherwise>IMBALANCE DETECTED</c:otherwise></c:choose>
        </div>

        <%-- Summary KPIs --%>
        <div class="row g-3 mb-4">
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Total Assets</small><h4 class="mb-0"><fmt:formatNumber value="${bsData.totalAssets}" type="currency" currencySymbol="&#8377;" maxFractionDigits="0"/></h4></div></div>
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Total Liabilities</small><h4 class="mb-0"><fmt:formatNumber value="${bsData.totalLiabilities}" type="currency" currencySymbol="&#8377;" maxFractionDigits="0"/></h4></div></div>
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Total Equity</small><h4 class="mb-0"><fmt:formatNumber value="${bsData.totalEquity}" type="currency" currencySymbol="&#8377;" maxFractionDigits="0"/></h4></div></div>
        </div>

        <%-- Statement Sections --%>
        <c:forEach var="section" items="${bsData.sections}">
        <div class="card shadow mb-4 reg-card">
            <div class="card-header bg-white"><h5 class="mb-0"><c:out value="${section.section}"/></h5></div>
            <div class="card-body">
                <table class="table table-sm reg-table">
                    <thead class="table-light">
                        <tr><th>Line Item</th><th>GL Code</th><th>Sub-Section</th><th class="text-end">Amount</th></tr>
                    </thead>
                    <tbody>
                        <c:forEach var="line" items="${section.lines}">
                        <tr>
                            <td><c:out value="${line.lineName}"/></td>
                            <td><code><c:out value="${line.glCode}"/></code></td>
                            <td><small class="text-muted"><c:out value="${line.subSection}"/></small></td>
                            <td class="text-end"><fmt:formatNumber value="${line.amount}" maxFractionDigits="2"/></td>
                        </tr>
                        </c:forEach>
                    </tbody>
                    <tfoot class="table-light fw-bold">
                        <tr><td colspan="3">Section Total</td><td class="text-end"><fmt:formatNumber value="${section.sectionTotal}" maxFractionDigits="2"/></td></tr>
                    </tfoot>
                </table>
            </div>
        </div>
        </c:forEach>

        <c:if test="${bsSnapshot != null}">
        <div class="audit-disclaimer mt-3"><i class="bi bi-shield-lock"></i> Snapshot: <c:out value="${bsSnapshot.generatedAt}"/> | Hash: <code>${bsSnapshot.hashChecksum.substring(0, 16)}...</code> | Generated by EOD | Status: FINAL | Derived from immutable ledger entries only.</div>
        </c:if>
    </c:when>
    <c:otherwise>
        <div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i> Balance Sheet snapshot not available for <c:out value="${businessDate}"/>. Run EOD to generate.</div>
    </c:otherwise>
</c:choose>

<%@ include file="../layout/footer.jsp" %>
