<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ include file="../layout/header.jsp" %>
<link rel="stylesheet" href="${pageContext.request.contextPath}/resources/css/regulatory.css"/>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h3><i class="bi bi-graph-up-arrow"></i> Profit & Loss Statement — RBI Schedule 14</h3>
    <div>
        <span class="badge bg-dark me-2"><i class="bi bi-calendar3"></i> <c:out value="${businessDate}"/></span>
        <span class="eod-verified"><i class="bi bi-check-circle-fill"></i> EOD Verified</span>
    </div>
</div>
<%@ include file="../layout/status-banner.jsp" %>

<c:choose>
    <c:when test="${pnlAvailable}">
        <%-- Summary KPIs --%>
        <div class="row g-3 mb-4">
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Total Revenue</small><h4 class="mb-0 text-success"><fmt:formatNumber value="${pnlData.totalRevenue}" type="currency" currencySymbol="&#8377;" maxFractionDigits="2"/></h4></div></div>
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Total Expense</small><h4 class="mb-0 text-danger"><fmt:formatNumber value="${pnlData.totalExpense}" type="currency" currencySymbol="&#8377;" maxFractionDigits="2"/></h4></div></div>
            <div class="col-md-4"><div class="reg-kpi-card text-center"><small class="text-muted d-block">Net Profit</small><h4 class="mb-0 ${pnlData.netProfit >= 0 ? 'text-success' : 'text-danger'}"><fmt:formatNumber value="${pnlData.netProfit}" type="currency" currencySymbol="&#8377;" maxFractionDigits="2"/></h4></div></div>
        </div>

        <%-- Statement Sections --%>
        <c:forEach var="section" items="${pnlData.sections}">
        <div class="card shadow mb-4 reg-card">
            <div class="card-header bg-white"><h5 class="mb-0"><c:out value="${section.section}"/></h5></div>
            <div class="card-body">
                <table class="table table-sm reg-table">
                    <thead class="table-light">
                        <tr><th>Line Item</th><th>GL Code</th><th class="text-end">Amount</th></tr>
                    </thead>
                    <tbody>
                        <c:forEach var="line" items="${section.lines}">
                        <tr>
                            <td><c:out value="${line.lineName}"/></td>
                            <td><code><c:out value="${line.glCode}"/></code></td>
                            <td class="text-end"><fmt:formatNumber value="${line.amount}" maxFractionDigits="2"/></td>
                        </tr>
                        </c:forEach>
                    </tbody>
                    <tfoot class="table-light fw-bold">
                        <tr><td colspan="2">Section Total</td><td class="text-end"><fmt:formatNumber value="${section.sectionTotal}" maxFractionDigits="2"/></td></tr>
                    </tfoot>
                </table>
            </div>
        </div>
        </c:forEach>

        <%-- Net Profit Summary --%>
        <div class="card shadow mb-4 border-primary">
            <div class="card-body text-center py-3">
                <h4 class="mb-0">Net Profit: <span class="${pnlData.netProfit >= 0 ? 'text-success' : 'text-danger'}"><fmt:formatNumber value="${pnlData.netProfit}" type="currency" currencySymbol="&#8377;" maxFractionDigits="2"/></span></h4>
            </div>
        </div>

        <c:if test="${pnlSnapshot != null}">
        <div class="audit-disclaimer mt-3"><i class="bi bi-shield-lock"></i> Snapshot: <c:out value="${pnlSnapshot.generatedAt}"/> | Hash: <code>${pnlSnapshot.hashChecksum.substring(0, 16)}...</code> | Generated by EOD | Status: FINAL</div>
        </c:if>
    </c:when>
    <c:otherwise>
        <div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i> P&L snapshot not available for <c:out value="${businessDate}"/>. Run EOD to generate.</div>
    </c:otherwise>
</c:choose>

<%@ include file="../layout/footer.jsp" %>
