package com.ledgora.loan.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Loan schedule preview DTO — Finacle LACSMNT pre-disbursement schedule view.
 *
 * <p>Generated by {@code LoanDisbursementService.previewSchedule()} without persisting. Displayed
 * to the maker before confirming disbursement per CBS two-step onboarding.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LoanSchedulePreviewDTO {

    private String productCode;
    private String productName;
    private BigDecimal interestRate;
    private String interestType;
    private int tenureMonths;
    private BigDecimal principalAmount;
    private BigDecimal emiAmount;
    private BigDecimal totalInterestPayable;
    private BigDecimal totalAmountPayable;
    private LocalDate firstEmiDate;
    private LocalDate lastEmiDate;
    private List<Installment> installments;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Installment {
        private int number;
        private LocalDate dueDate;
        private BigDecimal emiAmount;
        private BigDecimal principalComponent;
        private BigDecimal interestComponent;
        private BigDecimal outstandingAfter;
    }
}
